# Makefile for hello pass

# Path to top level of LLVM hierarchy
LEVEL = ../../..

# Name of the library to build
LIBRARYNAME = LLVMInstrumenter
BUILD_ARCHIVE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common
